# Generated by Django 3.2.2 on 2021-08-24 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_alter_event_date'),
        ('Event', '0003_userjoined'),
    ]

    operations = [
    ]
