# Generated by Django 3.2.2 on 2021-05-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0011_alter_account_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='avatar',
        ),
    ]
