# Generated by Django 3.2.2 on 2021-05-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0012_remove_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ImageField(default='defaultAvatar.png', upload_to='Avatar/'),
        ),
    ]
