# Generated by Django 3.2.2 on 2021-05-13 13:28

import Auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0015_auto_20210513_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(validators=[Auth.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
