# Generated by Django 3.2.2 on 2021-05-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0017_alter_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='show_gender',
            field=models.BooleanField(default=True),
        ),
    ]
