# Generated by Django 3.2.2 on 2021-05-13 14:01

import Auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0021_alter_account_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=25, validators=[Auth.validators.validate_not_null_string]),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(max_length=25, validators=[Auth.validators.validate_not_null_string]),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=50, validators=[Auth.validators.validate_not_null_string]),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(max_length=10, validators=[Auth.validators.validate_not_null_string]),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=50, validators=[Auth.validators.validate_not_null_string]),
        ),
    ]
