# Generated by Django 3.2.2 on 2021-05-13 14:10

import Auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0023_alter_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.IntegerField(validators=[Auth.validators.validate_gender]),
        ),
    ]
