# Generated by Django 3.2.2 on 2021-05-13 14:14

import Auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0024_alter_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(default=18, validators=[Auth.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(default='', max_length=25, validators=[Auth.validators.validate_not_null_string]),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(default='', max_length=25, validators=[Auth.validators.validate_not_null_string]),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='', max_length=50, validators=[Auth.validators.validate_not_null_string]),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.IntegerField(default=0, validators=[Auth.validators.validate_gender]),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=50, validators=[Auth.validators.validate_not_null_string]),
        ),
    ]
