# Generated by Django 3.2.2 on 2021-06-11 09:18

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0026_auto_20210522_0951'),
    ]

    operations = [
        UnaccentExtension()
    ]
