# Generated by Django 3.2.2 on 2021-05-29 15:48

import Auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0026_auto_20210522_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(14)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=25, validators=[Auth.validators.validate_not_null_string]),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(max_length=25, validators=[Auth.validators.validate_not_null_string]),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=50, validators=[Auth.validators.validate_not_null_string]),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=50, validators=[Auth.validators.validate_not_null_string]),
        ),
    ]
