# Generated by Django 3.2.2 on 2021-06-11 09:21

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0027_auto_20210611_0918'),
    ]

    operations = [
        TrigramExtension()
    ]
