# Generated by Django 3.2.2 on 2021-06-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0027_auto_20210529_1748'),
        ('Auth', '0028_auto_20210611_0921'),
    ]

    operations = [
    ]
