# Generated by Django 3.2.2 on 2021-08-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0030_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nationality',
            field=models.CharField(choices=[('FRE', 'Français'), ('JAP', 'Japonais')], default='FRE', max_length=3),
        ),
    ]
